[[mgr.prepend_keymap]]
on   = "E"
run  = 'shell -- ${VISUAL:-$EDITOR} %d'
desc = "Open current directory in $VISUAL"

[[mgr.prepend_keymap]]
on   = "<S-Enter>"
run  = 'shell -- ${VISUAL:-$EDITOR} %h'
desc = "Open in $VISUAL"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "<C-f>"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = ["g", "i"]
run  = "plugin lazygit"
desc = "Open lazygit"

[[mgr.prepend_keymap]]
on   = "<A-y>"
run  = "plugin copy-file-contents"
desc = "Copy file contents to clipboard"

[[mgr.prepend_keymap]]
on   = "o"
run  = "plugin open-with-cmd -- block"
desc = "Open with command in terminal"

[[mgr.prepend_keymap]]
on   = "O"
run  = "plugin open-with-cmd"
desc = "Open with command in background"

[[mgr.prepend_keymap]]
on   = "<Backspace>"
run  = "leave"
desc = "Go to parent directory"

[[mgr.prepend_keymap]]
on   = "d"
run  = "noop"
desc = "Disabled"

[[mgr.prepend_keymap]]
on   = "D"
run  = "noop"
desc = "Disabled"

[[mgr.prepend_keymap]]
on   = "<Delete>"
run  = "remove"
desc = "Trash selected files"

[[mgr.prepend_keymap]]
on   = "q"
run  = "quit --no-cwd-file"
desc = "Quit without changing directory"

[[mgr.prepend_keymap]]
on   = "Q"
run  = "quit"
desc = "Quit and cd to current directory"

[[mgr.prepend_keymap]]
on   = "?"
run  = "help"
desc = "Show keybindings help"

[[mgr.prepend_keymap]]
on   = "<C-y>"
run  = 'shell "echo %s | cb" --orphan'
desc = "Copy file path to clipboard"

# Bookmarks (yamb)
[[mgr.prepend_keymap]]
on   = ["u", "a"]
run  = "plugin yamb save"
desc = "Bookmark: save current dir"

[[mgr.prepend_keymap]]
on   = ["u", "g"]
run  = "plugin yamb jump_by_key"
desc = "Bookmark: jump by key"

[[mgr.prepend_keymap]]
on   = ["u", "G"]
run  = "plugin yamb jump_by_fzf"
desc = "Bookmark: jump by fzf"

[[mgr.prepend_keymap]]
on   = ["u", "d"]
run  = "plugin yamb delete_by_key"
desc = "Bookmark: delete by key"

[[mgr.prepend_keymap]]
on   = ["u", "r"]
run  = "plugin yamb rename_by_key"
desc = "Bookmark: rename by key"
