"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 800

format = """
[ÓÇ∂](#9A348E)\
$username\
[ÓÇ∞](bg:#DA627D fg:#9A348E)\
$directory\
[ÓÇ∞](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_state\
$git_status\
[ÓÇ∞](fg:#FCA17D bg:#86BBD8)\
$golang\
$nodejs\
$rust\
[ÓÇ∞](fg:#86BBD8 bg:#33658A)\
$time\
[ÓÇ∞](fg:#33658A bg:#FEF08A)\
$aws\
[ÓÇ∞](fg:#FEF08A)\
\n\n\
$character\
"""

[aws]
format = '[ $symbol( $profile )(\($region\))]($style)'
style = 'bg:#FEF08A fg:#000000'
symbol = 'üÖ∞ '
[aws.profile_aliases]
self-hosted-ci-freecodecamp = 'fcc-ci'

[username]
format = '[$user ]($style)'
show_always = true
style_root = "bg:#9A348E"
style_user = "bg:#9A348E"

[hostname]
disabled = false
format = "[$ssh_symbol](bold blue) on [$hostname](bold red)"
ssh_only = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
read_only_style = "bg:#DA627D fg:#FCA17D"
style = "bg:#DA627D"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "‚Ä¶/"

[directory.substitutions]
"Documents" = "Ôúò "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "
"Videos" = "ÔÄΩ "

[time]
disabled = false
format = "[ ‚ô• $time ]($style)"
style = "bg:#33658A"
time_format = "%R"

[git_branch]
format = '[ $symbol$branch]($style)'
style = "black bg:#FCA17D"
symbol = "Ôêò "

[git_state]
format = '[ $symbol$state($progress_current/$progress_total)]($style)'
style = "black bg:#FCA17D"

[git_status]
format = '[ $all_status$ahead_behind ]($style)'
style = "black bg:#FCA17D"

[golang]
format = '[ $symbol ($version) ]($style)'
style = "black bg:#86BBD8"
symbol = "Óòß"

[memory_usage]
format = '[ $symbol ($version) ]($style)'
style = "black bg:#86BBD8"
symbol = "Ô°ö"

[nodejs]
format = '[ $symbol ($version) ]($style)'
style = "black bg:#86BBD8"
symbol = "Óúò"

[package]
format = '[ $symbol ($version) ]($style)'
style = "black bg:#86BBD8"
symbol = "Ô£ñ"

[python]
format = '[ $symbol ($version) ]($style)'
style = "black bg:#86BBD8"
symbol = "Óàµ "

[rust]
format = '[ $symbol ($version) ]($style)'
style = "black bg:#86BBD8"
symbol = "Óû®"
